### ISSUE TITLE
Include into htmlbars repo

### ISSUE THREAD

**Issue by mmun** [code0100fun/htmlbars-printer#1]
Do you mind if we pull this into the htmlbars-syntax package in tildeio/htmlbars? It seems useful. I can give you contributor access there as well.

**Comment by rwjblue** [comment]
:+1:

**Comment by code0100fun** [comment]
Yeah, that would be great. Still hashing out the BlockStatement inverse but it's close to being done. Also working on using the Handlebars visitor instead of the recursive build calls.

**Comment by mmun** [comment]
This effort has begun so I'll close this issue.
